[[redirects]]
  from = "/api"
  to = "https://partnerapi.funda.nl/feeds/Aanbod.svc/json"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200